- block:
    - yum: name=python27-psycopg2 state=present
      become: yes
      tags:
        - deps

    - file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
      become: yes
      tags:
        - config
      with_items:
        - /var/log/hope
        - "{{ app_home }}/.ssh"

    - name: set dbhost variable to RDS endpoint
      set_fact: dbhost="{{ rds.instance.endpoint }}"
      when: rds is defined

    - template:
        src: authorized_keys
        dest: "{{ app_home }}/.ssh/authorized_keys"
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
      tags:
        - config
  rescue:
    - include: rescue.yml state=common
