- block:
    - template: src=secret.py.j2 dest="{{ django_home }}/hopestarter/settings/secret.py"
      tags:
          - code
    - template: src=api_secret.py.j2 dest="{{ django_home }}/hopestarter/settings/api_secret.py"
      tags:
          - code
  rescue:
    - include: rescue.yml state=secrets
