- name: installing system-level dependencies
  yum: name={{ item }} state=present enablerepo=epel
  become: yes
  with_items:
      - git
      - postgresql94-devel
      - gcc
      - geos
      - gdal
      - nginx
      - zlib-devel
      - libjpeg-turbo-devel

- name: updating source code to {{ git_version }}
  git: repo={{ repo_url }} dest="{{ app_home }}/hopestarterapp" version={{ git_version }}
  notify: api changed

- name: installing virtualenv
  pip: name=virtualenv state=present extra_args="--user"

- name: upgrade pip
  pip: name=pip state=latest virtualenv="{{ app_home }}/venv/" virtualenv_site_packages=yes

- name: installing python dependencies
  pip: requirements="{{ app_home }}/hopestarterapp/requirements/production_api.txt" virtualenv="{{ venv_path }}" virtualenv_site_packages=yes
  notify: api changed
