- block:
    - name: setup env
      template: src=envrc.j2 dest="{{ app_home }}/.envrc"
      tags: ['config']
      notify: api changed

    - name: configuring AWS_ACCESS_KEY_ID
      lineinfile:
        create: yes
        state: present
        dest: "{{ app_home }}/.env/AWS_ACCESS_KEY_ID"
        line: "{{ aws_api_key }}"
      no_log: true
      tags: ['config']
      notify: api changed

    - name: configuring AWS_SECRET_ACCESS_KEY
      lineinfile:
        create: yes
        state: present
        dest: "{{ app_home }}/.env/AWS_SECRET_ACCESS_KEY"
        line: "{{ aws_api_secret }}"
      no_log: true
      tags: ['config']
      notify: api changed

    - include: code.yml
      tags: ['code']

    - include: nginx.yml
      tags: ['config']

    - include: django.yml

    - name: installing uWSGI vassal configuration
      template: src=vassal-api.ini.j2 dest="{{ app_home }}/vassals/api.ini"
      tags:
          - config
          - code
      notify: api changed
  rescue:
    - include: rescue.yml state=api
