- name: restart_nginx
  service: name=nginx state=reloaded
  become: yes
  tags:
      - config

- name: api changed
  file: path="{{ app_home }}/vassals/api.ini" state=touch
  tags:
      - config
      - code
